name: Build PyInstaller Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: PyInstaller Action
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: 3.11
        requirements: requirements.txt
        # py: main.py
        spec: main.py
        exe_path: ./dist
        upload_exe_with_name: some_exe
